import 'package:hive/hive.dart';

part 'game_stats.g.dart'; // Generated by build_runner

/// Hive model for persisting game statistics
@HiveType(typeId: 0)
class GameStats extends HiveObject {
  @HiveField(0)
  int highScore;

  @HiveField(1)
  int totalGamesPlayed;

  @HiveField(2)
  int totalCorrectAnswers;

  GameStats({
    this.highScore = 0,
    this.totalGamesPlayed = 0,
    this.totalCorrectAnswers = 0,
  });

  /// Calculates the win rate as a percentage
  /// Win rate = totalCorrectAnswers / (totalGamesPlayed * 10) * 100
  double get winRate => totalGamesPlayed == 0
      ? 0
      : (totalCorrectAnswers / (totalGamesPlayed * 10) * 100);
}